// ═══════════════════════════════════════════════════════════════════
//  PMP EXAM MASTERY — Expanded Flashcard Deck (75 Cards)
//  Categories: pmbok6 | pmbok7 | agile | evm | risk | contracts
//  Exposed as window.PMP_FLASHCARDS for app.js to consume.
// ═══════════════════════════════════════════════════════════════════
window.PMP_FLASHCARDS = [

  // ─────────────────── PMBOK 6 PROCESS GROUPS & KNOWLEDGE AREAS ───────────────────
  { cat: 'pmbok6', q: 'What are the 5 Process Groups?', a: 'Initiating, Planning, Executing, Monitoring & Controlling, and Closing. They are NOT sequential phases — they overlap and repeat throughout the project.' },
  { cat: 'pmbok6', q: 'How many Knowledge Areas and Processes are in PMBOK 6?', a: '10 Knowledge Areas containing 49 processes total. Integration is the only KA with processes in ALL 5 process groups.' },
  { cat: 'pmbok6', q: 'What is the difference between Validate Scope and Control Quality?', a: 'Validate Scope = formal ACCEPTANCE of deliverables by the customer (external-facing). Control Quality = verifying deliverables meet quality REQUIREMENTS (internal-facing). Control Quality happens BEFORE Validate Scope.' },
  { cat: 'pmbok6', q: 'What is a Project Charter?', a: 'A document issued by the project SPONSOR that formally authorizes the existence of a project and provides the PM with authority to apply organizational resources. Created in the Initiating process group.' },
  { cat: 'pmbok6', q: 'What is Perform Integrated Change Control?', a: 'The process of reviewing all change requests, approving/rejecting changes, and managing changes to deliverables, documents, and the PM plan. The CCB (Change Control Board) makes approval decisions.' },
  { cat: 'pmbok6', q: 'What is the Critical Path Method (CPM)?', a: 'A schedule network analysis technique that identifies the longest path through the project. Activities on the critical path have ZERO total float. Any delay directly delays project end date.' },
  { cat: 'pmbok6', q: 'Name the 5 conflict resolution techniques in order of PMP preference', a: '1) Collaborate/Problem-Solve (best — win-win), 2) Compromise/Reconcile (lose-lose), 3) Smooth/Accommodate (temporary), 4) Force/Direct (win-lose), 5) Withdraw/Avoid (postpone). PMI always prefers Collaborate.' },
  { cat: 'pmbok6', q: 'What is the difference between OPA and EEF?', a: 'OPA (Organizational Process Assets) = internal processes, policies, templates, lessons learned — things the org CONTROLS. EEF (Enterprise Environmental Factors) = conditions the team CANNOT control (market, regulations, culture).' },
  { cat: 'pmbok6', q: 'What are the 4 types of project dependencies?', a: 'Mandatory (hard logic), Discretionary (preferred/soft logic), External (outside project), Internal (within project). They can combine: e.g., External Mandatory.' },
  { cat: 'pmbok6', q: 'What is a Risk Register?', a: 'A document containing results of risk identification, qualitative & quantitative analysis, and risk response planning. It is a living document updated throughout the project — the primary output of Identify Risks.' },
  { cat: 'pmbok6', q: 'What are the risk response strategies for THREATS?', a: 'Avoid (eliminate the threat), Transfer (shift to third party), Mitigate (reduce probability/impact), Accept (active or passive), Escalate (beyond PM authority). PMI prefers proactive responses.' },
  { cat: 'pmbok6', q: 'What are the risk response strategies for OPPORTUNITIES?', a: 'Exploit (ensure it occurs), Share (allocate to best-positioned third party), Enhance (increase probability/impact), Accept, and Escalate.' },
  { cat: 'pmbok6', q: 'What process group has the MOST processes in PMBOK 6?', a: 'Planning — with 24 processes. This reflects PMI\'s emphasis on thorough planning before execution. Executing has 10, Monitoring & Controlling has 12, Initiating has 2, Closing has 1.' },
  { cat: 'pmbok6', q: 'What is the Scope Baseline?', a: 'The approved version of: (1) Project Scope Statement, (2) WBS, and (3) WBS Dictionary. All three together form the Scope Baseline — the standard against which scope performance is measured.' },
  { cat: 'pmbok6', q: 'What is the difference between crashing and fast-tracking?', a: 'Crashing = adding resources to critical path activities — reduces duration but INCREASES COST. Fast-tracking = overlapping activities that were planned sequentially — no added cost but INCREASES RISK of rework.' },
  { cat: 'pmbok6', q: 'What is resource leveling vs resource smoothing?', a: 'Leveling adjusts dates based on resource constraints — CAN extend the project and change the critical path. Smoothing delays non-critical activities within their float — does NOT change the critical path or project end date.' },
  { cat: 'pmbok6', q: 'What is the Communication Channels formula?', a: 'N × (N-1) / 2, where N = number of stakeholders (including PM). Example: 10 stakeholders = 10 × 9 / 2 = 45 channels. Every new stakeholder exponentially increases communication complexity.' },
  { cat: 'pmbok6', q: 'What are the three types of project estimates?', a: 'Rough Order of Magnitude (ROM): −25% to +75% accuracy (early). Budget Estimate: −10% to +25%. Definitive Estimate: −5% to +10% (late in planning). Accuracy improves as project detail increases (Cone of Uncertainty).' },
  { cat: 'pmbok6', q: 'What is the difference between a contingency reserve and a management reserve?', a: 'Contingency Reserve: for KNOWN UNKNOWNS (identified risks). Controlled by the PM. INCLUDED in the cost baseline. Management Reserve: for UNKNOWN UNKNOWNS (unforeseen events). Controlled by senior management. NOT in the cost baseline.' },
  { cat: 'pmbok6', q: 'What is a Work Package?', a: 'The lowest level of the WBS where cost and duration can be reliably estimated and managed. Work Packages can be decomposed further into activities for schedule planning. They are NOT necessarily one task.' },
  { cat: 'pmbok6', q: 'What is the key output of Validate Scope?', a: 'Accepted Deliverables — formally signed off by the customer or sponsor. These are then used as input to Close Project or Phase. Rejected deliverables generate Change Requests.' },
  { cat: 'pmbok6', q: 'What is the RACI chart?', a: 'A Responsibility Assignment Matrix. R = Responsible (does the work), A = Accountable (owns the outcome, signs off), C = Consulted (provides input), I = Informed (receives updates). Only ONE person should be Accountable per task.' },
  { cat: 'pmbok6', q: 'What is a Project Management Information System (PMIS)?', a: 'An automated system used to gather, integrate, and disseminate project information. It is the primary tool for Direct & Manage Project Work and many other executing and monitoring processes.' },
  { cat: 'pmbok6', q: 'What is the difference between Project, Program, and Portfolio?', a: 'Project: temporary, creates unique result. Program: group of RELATED projects managed together for strategic benefits. Portfolio: collection of projects/programs aligned to STRATEGIC OBJECTIVES. Benefits increase at each level.' },

  // ─────────────────── PMBOK 7 PRINCIPLES & DOMAINS ───────────────────
  { cat: 'pmbok7', q: 'How does PMBOK 7 fundamentally differ from PMBOK 6?', a: 'PMBOK 6 is PROCESS-based (prescriptive — 49 processes, ITTOs). PMBOK 7 is PRINCIPLE-based (descriptive — 12 principles, 8 performance domains). PMBOK 7 focuses on OUTCOMES and supports ALL development approaches (predictive, agile, hybrid).' },
  { cat: 'pmbok7', q: 'What is the System for Value Delivery?', a: 'A collection of strategic business activities aimed at building, sustaining, and advancing an organization. Projects, programs, portfolios, and operations are components that interact to deliver value to stakeholders.' },
  { cat: 'pmbok7', q: 'Name the 12 PMBOK 7 Principles', a: '1.Stewardship 2.Collaborative Team 3.Stakeholders 4.Value 5.Systems Thinking 6.Leadership 7.Tailoring 8.Quality 9.Complexity 10.Risk 11.Adaptability 12.Change. Remember: "Stewards Create Valuable Systems — Leaders Tailor Quality Complexity, Risk Adaptation Creates Change."' },
  { cat: 'pmbok7', q: 'What does the Tailoring principle mean?', a: 'Design the project development approach based on the unique context — project size, complexity, org culture, regulatory environment, risk. No one-size-fits-all methodology. Tailor processes, tools, techniques, and governance to "just enough."' },
  { cat: 'pmbok7', q: 'What are the 8 Performance Domains of PMBOK 7?', a: '1.Stakeholder 2.Team 3.Development Approach & Life Cycle 4.Planning 5.Project Work 6.Delivery 7.Measurement 8.Uncertainty. They form an interdependent system — changes in one domain affect all others.' },
  { cat: 'pmbok7', q: 'What is the "Focus on Value" principle?', a: 'Value is the ultimate indicator of project success — not just completing deliverables. Continuously evaluate alignment to business objectives and intended benefits. Value can include financial returns, social good, or strategic positioning. Outcomes > Outputs.' },
  { cat: 'pmbok7', q: 'How do PMBOK 7 Performance Domains interact?', a: 'They form an interactive, interrelated, and interdependent system. No domain operates in isolation. Evaluated by OUTCOMES (desired results) not process adherence. A problem in the Uncertainty domain affects Delivery and Measurement.' },
  { cat: 'pmbok7', q: 'What is the Stewardship principle?', a: 'Act responsibly with integrity, care, trustworthiness, and compliance. Stewards consider financial, social, technical, and environmental impacts of their decisions. Balance organizational objectives with the needs of global stakeholders.' },
  { cat: 'pmbok7', q: 'What does the Complexity principle address?', a: 'Continuously evaluate and navigate project complexity arising from human behavior, system interactions, and ambiguity. Simplify where possible; use iterative approaches for high complexity. Build in buffers and flexibility.' },
  { cat: 'pmbok7', q: 'What is the Embrace Adaptability and Resiliency principle?', a: 'Build the capability to anticipate, respond to, and recover from setbacks. Resilient teams and organizations bounce back from disruptions quickly and continue to advance project objectives. Continuous learning is key.' },

  // ─────────────────── AGILE / SCRUM ───────────────────
  { cat: 'agile', q: 'What is a Servant Leader?', a: 'A leadership style where the leader\'s primary goal is to SERVE the team. In Scrum, the Scrum Master is a servant leader — they remove impediments, coach self-organization, shield the team from interference, and facilitate (not direct) the work.' },
  { cat: 'agile', q: 'What is the Definition of Done (DoD)?', a: 'A shared understanding of what it means for work to be COMPLETE, including quality standards, testing criteria, and documentation requirements. Every increment must meet the DoD before it can be considered potentially releasable.' },
  { cat: 'agile', q: 'What is a Sprint Burndown Chart?', a: 'A graph showing remaining work (Y-axis) vs. days in sprint (X-axis). Ideal line slopes from total story points on Day 1 to zero on the last day. Teams use it to predict if they will complete the Sprint Goal.' },
  { cat: 'agile', q: 'Who can cancel a Sprint, and why?', a: 'ONLY the Product Owner can cancel a Sprint. This happens when the Sprint Goal becomes obsolete — usually due to a major market change, technology shift, or executive direction. Cancelled sprints are rare and disruptive.' },
  { cat: 'agile', q: 'What is Backlog Refinement (Grooming)?', a: 'An ongoing activity where the Product Owner and Development Team review backlog items: adding detail, estimating effort, clarifying acceptance criteria, and reordering by priority. Consumes no more than 10% of team capacity. NOT one of the 5 official Scrum events.' },
  { cat: 'agile', q: 'What is Kanban and its key constraint?', a: 'A visual workflow management method using a board with columns (To Do, In Progress, Done). Key concept: WIP (Work In Progress) LIMITS — restricting how many items can be in any stage at once to optimize flow and reduce bottlenecks.' },
  { cat: 'agile', q: 'What is the Agile Iron Triangle?', a: 'In Traditional PM: Scope is FIXED, Time & Cost are estimated. In Agile: Time & Cost are FIXED (sprint length, team size), Scope is the VARIABLE. Agile delivers the highest-value features first, accepting scope flexibility.' },
  { cat: 'agile', q: 'What are the 5 Scrum Events (Ceremonies)?', a: '1. Sprint (the container — 1-4 weeks). 2. Sprint Planning. 3. Daily Scrum (15 min standup). 4. Sprint Review (demo to stakeholders). 5. Sprint Retrospective (inspect how we worked). All are timeboxed.' },
  { cat: 'agile', q: 'What is the role of the Product Owner in Scrum?', a: 'Owns the Product Backlog. Maximizes product value. Represents stakeholders. One person, not a committee. Decides priority. The PO is the single point of authority for what gets built and in what order.' },
  { cat: 'agile', q: 'What is Velocity in Agile?', a: 'The amount of work (story points or items) a team completes in a sprint. Measured over multiple sprints to establish a reliable baseline. Used to forecast future sprint capacity and release dates. It is a planning tool, not a performance metric.' },
  { cat: 'agile', q: 'What is the Minimum Viable Product (MVP)?', a: 'The smallest version of a product that delivers enough value to satisfy early adopters and validate a hypothesis. The MVP is released to gather feedback, not as a finished product. It reduces waste by testing assumptions before full investment.' },
  { cat: 'agile', q: 'What is the difference between Sprint Review and Sprint Retrospective?', a: 'Sprint Review: WHAT was built — demo of the working increment to stakeholders; backlog is updated. Sprint Retrospective: HOW the team worked — inspect processes, tools, relationships; create improvement action items. Retro is AFTER the Review.' },
  { cat: 'agile', q: 'What does "potentially shippable product increment" mean?', a: 'At the end of each Sprint, the Development Team must produce a working, integrated, tested increment that meets the Definition of Done. It doesn\'t have to be shipped, but it COULD be — no additional work should be needed to release it.' },
  { cat: 'agile', q: 'What is the Tuckman Model of team development?', a: 'Forming (polite, unclear roles) → Storming (conflict, asserting positions) → Norming (establishing norms, collaboration improves) → Performing (high-performance, self-organizing) → Adjourning (project ends, team disbands). PMs adjust leadership at each stage.' },

  // ─────────────────── EARNED VALUE MANAGEMENT (EVM) ───────────────────
  { cat: 'evm', q: 'What does CPI < 1.0 mean?', a: 'The project is OVER BUDGET. For every $1 spent, less than $1 of value is earned. CPI = EV / AC. Example: CPI = 0.80 means only $0.80 of value per $1 spent. CPI is the most predictive EVM metric on the PMP exam.' },
  { cat: 'evm', q: 'What does SPI > 1.0 mean?', a: 'The project is AHEAD OF SCHEDULE. SPI = EV / PV. Example: SPI = 1.20 means 20% more work completed than planned. Warning: SPI becomes unreliable near project end because PV and EV both approach BAC regardless of true performance.' },
  { cat: 'evm', q: 'What are the 4 EAC formula variants and when to use each?', a: '1. EAC = BAC / CPI (current variance is TYPICAL, will continue). 2. EAC = AC + (BAC − EV) (original estimate was ATYPICAL — reset). 3. EAC = AC + [(BAC−EV) / (CPI×SPI)] (both cost and schedule impact). 4. EAC = AC + new estimate (team re-estimates remaining work).' },
  { cat: 'evm', q: 'What is TCPI and what does TCPI > 1.0 mean?', a: 'TCPI = (BAC − EV) / (BAC − AC). It shows the required future cost efficiency to meet the budget target. TCPI > 1.0 means you must perform BETTER than current CPI to stay on budget. TCPI = 1.0 means no improvement needed.' },
  { cat: 'evm', q: 'What is the difference between EAC, ETC, and VAC?', a: 'EAC = Estimate at Completion (total forecasted cost). ETC = Estimate to Complete (remaining cost needed = EAC − AC). VAC = Variance at Completion (expected surplus/deficit = BAC − EAC). Negative VAC = over budget at end.' },
  { cat: 'evm', q: 'PV vs EV vs AC — define each precisely', a: 'PV = Planned Value: budgeted cost of SCHEDULED work (what you planned to spend by now). EV = Earned Value: budgeted cost of COMPLETED work (progress in $ terms). AC = Actual Cost: what you ACTUALLY spent. EV is the cornerstone — it always appears on the left in variance formulas.' },
  { cat: 'evm', q: 'A project has CPI = 0.75 and SPI = 0.80. What does this mean?', a: 'The project is BOTH over budget AND behind schedule. For every $1 spent, only $0.75 of work is completed (over budget). Only 80% of scheduled work has been completed (behind schedule). This double-negative situation requires immediate corrective action.' },
  { cat: 'evm', q: 'What is the Cost Baseline and how is it represented?', a: 'The approved time-phased budget (funds allocated over time), often displayed as an S-curve. The Cost Baseline EXCLUDES management reserves but INCLUDES contingency reserves. It is the benchmark for measuring cost performance.' },
  { cat: 'evm', q: 'If BAC = $500K, EV = $300K, AC = $350K — calculate CV, SPI, and EAC', a: 'CV = EV − AC = $300K − $350K = −$50K (over budget). CPI = 300/350 = 0.857. EAC = BAC/CPI = $500K/0.857 = $583,400. The project will overspend by $83,400 if current performance continues.' },
  { cat: 'evm', q: 'What does Schedule Variance (SV) tell you, and what is its limitation?', a: 'SV = EV − PV. Positive = ahead of schedule; Negative = behind. LIMITATION: SV always approaches $0 at project end (because EV → BAC and PV → BAC), so it becomes meaningless in the final stages. Use schedule variance in time (SVt) from Earned Schedule theory for late-project accuracy.' },

  // ─────────────────── RISK MANAGEMENT ───────────────────
  { cat: 'risk', q: 'What is the difference between a risk and an issue?', a: 'Risk = uncertain event that MAY occur in the future (positive or negative). Issue = a risk that HAS occurred or a problem that exists NOW. Issues require immediate response; risks require monitoring and response planning.' },
  { cat: 'risk', q: 'What is Qualitative vs Quantitative Risk Analysis?', a: 'Qualitative: prioritizes risks using Probability × Impact matrix — fast, subjective. Quantitative: numerically analyzes combined effect of risks on objectives (Monte Carlo simulation, Decision Tree) — objective, statistical, resource-intensive. Qualitative is done FIRST.' },
  { cat: 'risk', q: 'What is an Opportunity vs a Threat in risk management?', a: 'Both are risks (uncertain events). Threat = negative risk (could harm objectives). Opportunity = positive risk (could benefit objectives). PMI explicitly requires managing BOTH. Example opportunity response: Exploit, Share, Enhance, Accept.' },
  { cat: 'risk', q: 'What is a Risk Trigger (Watch List)?', a: 'A risk trigger (also called risk symptom or warning sign) is an indicator that a risk event is about to occur. Identifying triggers allows proactive response before the risk fully materializes. Documented in the Risk Register.' },
  { cat: 'risk', q: 'What is the difference between risk appetite, tolerance, and threshold?', a: 'Appetite = general attitude toward risk ("we are risk-averse"). Tolerance = acceptable variation range (e.g., ±10% cost). Threshold = the specific point that triggers escalation or response (e.g., if cost variance > 15%, escalate to sponsor).' },
  { cat: 'risk', q: 'What is a Fallback Plan vs Contingency Plan?', a: 'Contingency Plan = pre-planned response activated when a risk TRIGGER is detected. Fallback Plan = secondary response used when the contingency plan is INSUFFICIENT or fails. Both are documented in the Risk Register.' },

  // ─────────────────── CONTRACT TYPES ───────────────────
  { cat: 'contracts', q: 'What are the main types of Fixed-Price contracts?', a: 'FFP (Firm Fixed Price): seller bears all cost risk, most common. FP-EPA (Fixed Price with Economic Price Adjustment): adjusts for inflation. FPIF (Fixed Price Incentive Fee): seller earns more if performance exceeds targets. FFP = lowest risk for buyer.' },
  { cat: 'contracts', q: 'What are Cost-Reimbursable contract types?', a: 'CPFF (Cost Plus Fixed Fee): seller paid costs + fixed fee regardless of performance. CPIF (Cost Plus Incentive Fee): fee adjusts based on actual vs target cost. CPAF (Cost Plus Award Fee): fee based on subjective performance rating. Buyer bears most cost risk.' },
  { cat: 'contracts', q: 'What is a Time and Materials (T&M) contract?', a: 'A hybrid contract: pays for actual time (labor rates) and materials used. Has elements of both fixed-price (labor rates) and cost-reimbursable (actual costs). Best for staff augmentation or uncertain scope. Highest buyer risk if uncapped.' },
  { cat: 'contracts', q: 'Which contract type puts the MOST risk on the seller? On the buyer?', a: 'Most risk on SELLER: Firm Fixed Price (FFP) — seller must absorb all cost overruns. Most risk on BUYER: Cost Plus Fixed Fee (CPFF) — buyer pays whatever it costs. T&M is risky for buyer if uncapped. Understanding risk allocation is critical for PMP exam contract questions.' },
  { cat: 'contracts', q: 'What is a Statement of Work (SOW) vs Scope of Work?', a: 'SOW (Statement of Work) = a formal document describing what the vendor must provide: deliverables, specifications, timeline, acceptance criteria. Used in procurement. Scope of Work is a broader term sometimes used interchangeably but more often refers to internal project work description.' },
  { cat: 'contracts', q: 'What is Point of Total Assumption (PTA) in an FPIF contract?', a: 'PTA = the cost at which the seller assumes 100% of cost responsibility. Formula: PTA = ((Ceiling Price − Target Price) / Buyer\'s Share Ratio) + Target Cost. Above the PTA, the seller bears all additional costs — it effectively becomes a FFP at ceiling price.' },
];
